# Generated by Django 5.0 on 2024-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Time',
            field=models.TimeField(blank=True, max_length=255, null=True, verbose_name='time'),
        ),
    ]
