# Generated by Django 5.0 on 2024-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_transaction_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_open',
            name='Account_Number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='account_number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Account_Number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='account_number'),
        ),
    ]
