# Generated by Django 5.0 on 2024-01-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_alter_account_open_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Account_Number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='account_number'),
        ),
    ]
