# Generated by Django 5.0 on 2024-01-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_alter_transaction_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_open',
            name='Account_Number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='account_number'),
        ),
    ]
